services:
  dashboard:
    build:
      context: dashboard-ui
      dockerfile: Dockerfile
    ports:
    - "80:80"
    depends_on:
    - processing
    - analyzer

  receiver:
    image: victortran1449/receiver:receiver-app
    ports:
    - "8080:8080"
    env_file: ".env"
    depends_on:
    - kafka
    volumes:
      - ./logs:/app/logs
      - ./config/receiver:/app/config

  storage:
    image: victortran1449/storage:storage-app
    env_file: ".env"
    depends_on:
    - db
    - kafka
    volumes:
      - ./logs:/app/logs
      - ./config/storage:/app/config

  processing:
    image: victortran1449/processing:processing-app
    ports:
    - "8100:8100"
    env_file: ".env"
    depends_on:
    - storage
    volumes:
      - ./logs:/app/logs
      - ./config/processing:/app/config
      - ./data/processing:/app/data

  analyzer:
    image: victortran1449/receiver:receiver-app
    ports:
    - "8110:8110"
    env_file: ".env"
    depends_on:
    - kafka
    volumes:
      - ./logs:/app/logs
      - ./config/analyzer:/app/config

  zookeeper:
    image: wurstmeister/zookeeper
    volumes:
      - my-zookeeper:/opt/zookeeper-3.4.13/data

  kafka:
    image: wurstmeister/kafka
    command: [start-kafka.sh]
    environment:
      KAFKA_CREATE_TOPICS: "events:1:1"
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_LISTENERS: INSIDE://:29092,OUTSIDE://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /kafka/logs
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./data/kafka:/kafka
    depends_on:
      - "zookeeper"

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: livestream
    env_file: ".env" # Configure MYSQL_USER and MYSQL_PASSWORD based from storage conf
    volumes:
      - my-db:/var/lib/mysql
      - ./data/database:/docker-entrypoint-initdb.d

volumes:
  my-db:
  my-zookeeper: