version: 1
datastore:
  filename: data/processing.json
scheduler:
  interval: 5
eventstores:
  chat:
    url: http://storage:8090/stream/chats
  donation:
    url: http://storage:8090/stream/donations
